# Generated by Django 3.2.7 on 2023-05-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Firereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=250, null=True)),
                ('MobileNumber', models.CharField(max_length=12, null=True)),
                ('Location', models.CharField(max_length=200, null=True)),
                ('Message', models.CharField(max_length=200, null=True)),
                ('Status', models.CharField(max_length=150, null=True)),
                ('Postingdate', models.DateTimeField(auto_now_add=True)),
                ('AssignedTime', models.CharField(max_length=150, null=True)),
                ('UpdationDate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200, null=True)),
                ('teamLeaderName', models.CharField(max_length=250, null=True)),
                ('teamLeadMobno', models.CharField(max_length=15, null=True)),
                ('teamMembers', models.CharField(max_length=300, null=True)),
                ('postingDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firetequesthistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=250, null=True)),
                ('postingDate', models.DateTimeField(auto_now_add=True)),
                ('firereport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.firereport')),
            ],
        ),
        migrations.AddField(
            model_name='firereport',
            name='AssignTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.teams'),
        ),
    ]
